# Generated by Django 4.1.7 on 2023-05-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnews', '0004_category_name_en_us_category_name_ru_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ratingAuthor',
            field=models.SmallIntegerField(default=0, help_text='Рейтинг автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(default=0, help_text='Рейтинг поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Это текст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(help_text='Это текст поста', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(help_text='Это текст поста', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Это название текущего поста', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(help_text='Это название текущего поста', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(help_text='Это название текущего поста', max_length=128, null=True),
        ),
    ]
